pbaity/rocketchat-dark-mode

dark-mode.css
Added `.rc-modal__footer` class to the `body.dark-mode .rc-modal` rule.
=> Fixed white footer on file upload dialog

.gitignore, dark-mode-toggle.js, dark-mode.css
Hello @pbaity!
Thanks for this! We love having the night mode icon!
I fixed persistence not happening between sessions due to a logic error, I reworked the darkModeDefault logic a bit, I did some autoformatting, and I made two css changes 1) I didn't love visited links being bright magenta, and 2) I took out the part where you grew the footer logo to 100px and just kept it stock.
Cheers!
=> Changes we made for chat.gnome.org

dark-mode.css
That PR closes https://github.com/pbaity/rocketchat-dark-mode/issues/8
Result can be found in https://github.com/pbaity/rocketchat-dark-mode/issues/8#issuecomment-585022119
=> Fix Room Info text contrast

dark-mode.css
=> Apply dark mode to login

dark-mode.css
=> Apply input text color to input and textarea

dark-mode.css
closes #35 
this should just revert #22
=> Remove login page rules

dark-mode.css
Code snippets with diff highlighting are almost impossible to read. This commit changes the background color for deletions to a dark read color tone and for additions to a dark green color tone.
=> Make code snippet diffs easier to read

dark-mode-toggle.js
for #33
Using translation suggestion from @fdellwing
=> Add German translation

dark-mode.css
Original color is so dark you can hardly see it at all.
closes #46
=> Support visible green color for online contacts

dark-mode-toggle.js
=> Add Portuguese translation

dark-mode.css
Fixed issue with dropdown text being dark and therefor invisible
fixes #48
=> Fix invisible text in select elements

dark-mode-toggle.js
=> Added Hebrew translation

dark-mode.css
=> Fix connection status color

dark-mode.css
I've been dragging my feet to make this easy fix, but wanted to be sure nobody hated the colors.
Before:
After:
=> Update group and me mention colors

dark-mode-toggle.js
Hi, I've added Hungarian translation for the 'Toggle Dark Mode' text in dark-mode-toggle.js.
=> Hungarian translation for Toggle Dark Mode text.

dark-mode-toggle.js, dark-mode.css
Minimal initial changes to support dark mode in 3.8.0.
=> Initial changes for working with 3.8.0 (NOT backwards-compatible!)

dark-mode.css
- Dark admin menu
- Dark Channel/discussion options dialog
- Dark User modal
=> Changes for 3.9.1

dark-mode-toggle.js
=> Add French translation per @bseclier

dark-mode-toggle.js
Based on [this recommendation](https://github.com/pbaity/rocketchat-dark-mode/issues/97#issuecomment-755307260) from @antoine-roux.
=> Future-proof sidebar topbar selector

dark-mode.css
Hello,
There is a missing `}` here ;)
See you,
Antoine
=> Add missing bracket in CSS code

dark-mode.css
Fixes #99 with styles @pbaity, @UncleSamMericaMan and I collaborated on in our server.
=> Fixes for sidebar colors

dark-mode.css
Enable night mode for member list counter in the right hand side panel.
=> Enable night mode for member list counter

dark-mode.css
=> fix font color in text attachments

dark-mode.css
New version, new generated classes..
I opted to not use a generated class, but this might break other things. I clicked around in our instance and everything seemed good. But I cannot guarantee it.
=> font color in text attachment

dark-mode.css
- Fixes #121
- Fixes kinda the same issue, but for pinned messages announcement
- Fixes the background-color of panels' sidebars (css class has been changed)
Edit: Now also fixes #122 
Enjoy ;)
=> 3.12.x - Quotes, Pinned messages, Sidebar in panels

dark-mode-toggle.js
Update Italian translation for "toogle dark mode": 
Attiva/Disattiva modalità scura
=> update Italian translation

dark-mode.css
closes https://github.com/pbaity/rocketchat-dark-mode/issues/147
I didn't test if something else could be broken, but thread list fixed
=> Fix for thread list in 3.15.0

dark-mode.css
Fix text of Poll Application visibility in Dark Mode
=> [Fix] Text colors in Poll App

dark-mode.css
Fixes https://github.com/pbaity/rocketchat-dark-mode/issues/150 partly.
That fix appearance of user list in Create Direct Messages modal for example.
=> [Fix] User selector in some modals

dark-mode.css
See:
https://github.com/pbaity/rocketchat-dark-mode/issues/152
=> Fix banner colors and missing close button

dark-mode-toggle.js
=> Update Chinese Translation

dark-mode.css
This PR aims to fix #165, by modifying sidebar menus background and text colors (see screenshots below)
**Don't hesitate to give your thoughts on this !**
=> Sidebar menus colors

dark-mode.css
fixes #153 with @beloniki's suggested fix that I forgot about for months (sorry 🙄 )
Going to give everybody a bit to confirm along with me that this doesn't cause any unexpected changes elsewhere before I merge it.
=> Color pagination text on admin page

dark-mode.css
=> Fix invisible of user Names in group chats Member List

dark-mode.css
Hello there !
Two small fixes for 4.4.2
- Hover on channel members (linked to #168 
- Switch toggle color not visible
Didn't noticed any other issue related to new version, but don't hesitate to report them !
=> 4.4.2 (small fixes)

dark-mode.css
It was missing a close bracket in one of the classes at the end of the file. I just added it.
=> Hotfix - missing close bracket

dark-mode.css
=> Fix for Admin settings panels

dark-mode-toggle.js, dark-mode.css
This PR aims to solve (almost) all issues found in RocketChat `5.0.0`. As always, some (generated, and regular) classes changed, breaking some elements.
- ✅ Main chat messages (separator, action menu, popover ...)
- ✅ Thread chat messages 
- ✅ Admin panel information
- ✅ Admin panel sections
- ✅ Users information (Admin)
- ✅ Channel/Discussion tags (without breaking user roles tags, thanks @KeysBytes 😛 )
- ✅ Big refactor/improvement on buttons
- ✅ Big refactor/improvement on colors used for sidebar and channel header
- ✅ Marketplace Apps (list and individual info)
- ✅ Call modal (phone icon in channel)
Related : #189 - Thanks for reporting these issues 👌 
Don't hesitate to leave your thoughts 😉
=> Modifications for 5.0.0

dark-mode.css
**Describe your changes**
The new Apps section (formerly Marketplace) ended up inconsistent for theming compared to other Rocket.Chat sections, so it will require a lot of changes.
**Issues fixed**
This issue fixes (https://github.com/pbaity/rocketchat-dark-mode/issues/193)
**Screenshots**
=> Fix new Apps section in 5.1.0

dark-mode.css
Fixed unthemed elements in administrative workspace, introduced in 5.2.0. 
This affected the following pages:
- Administration -> Workspace -> Users
- Administration -> Workspace -> Rooms
- Administration -> Workspace -> Invites
- Administration -> Workspace -> View Logs
- Administration -> Workspace -> Custom Sounds
- Administration -> Workspace -> Email Inboxes
- Administration -> Workspace -> Custom Emoji
- Administration -> Workspace -> Integrations
- Administration -> Workspace -> Oauth Applications
- Administration -> Workspace -> Custom User Status
- Administration -> Workspace -> Permissions
- Administration -> Workspace -> Settings (element surround search bar when scrolling down)
- My Account -> Personal Access Tokens
This fixes #200. It is recommended to merge #196 and #198 for …
=> Fixed new unthemed elements in 5.2.0 workspace

dark-mode.css
I added some additional tweaks for 5.2.0:
- Reset the font color of messages to `var(--primary-font-color)`.
- Some minor issues when hovering messages.
- Some minor issues when editing messages.
Before:
https://user-images.githubusercontent.com/404840/196529273-f6cfb5a0-1dad-4730-be82-6b9dbd7bb88e.mp4
After:
https://user-images.githubusercontent.com/404840/196529296-09ef1319-f910-4ba0-99c1-62518fbdf612.mp4
=> Add some minor tweaks for 5.2.0

dark-mode.css
New RocketChat version 5.4.0 broke some elements, so I fixed them, and tried to improve rules and things while doing so
Top right buttons has styling issues, and some of the other buttons had incoherent behaviours. I tried to use variables as much as possible, to remove complicated custom rules 🥳 
We had a lot of rules related to quotes (and it looks like they were now useless or broken by 5.4.0), so I started over and tried **to match the normal behaviour, in dark mode**
In 5.4.0, global announcements are now in neutral color, with a small line of color, so I kept that behaviour. However, **I added back the color to channels announcements**, picking a more appropriate color for dark theme ("reverts" #206 😅 )
- Don't hesitate to report any issues found with 5.4.0 so I can fix them in that …
=> Modifications for 5.4.0
