pbaity/rocketchat-dark-mode

- dark-mode.css
I think this rule will bring back the border, which is necessary in dark mode to distinguish the colorless button ( `rc-button--nude` ).
> Fix borderless cancel button in file upload dialog

- dark-mode.css
Applying dark mode to a place it was missed - the user info panel that appears when you click on a user's name or avatar.
Before:
After:
> Apply dark mode to user info panel

- dark-mode.css
Fixes #10. There are two changes here: 1) variable settings to clean up the **Add Users** panel, and 2) setting `input` color to white universally. I want to mention that specifically since it seems like a major change.
New look for **Add Users** panel:
And when you select a user to add:
If universally setting the input text color to white seems like too much, somebody say so! But looking around, I think it's better that it be the default that can be overridden with specific rules where needed.
> Fix add user panel

- dark-mode-toggle.js
This translates (or will translate, once the translations get added) the label for the toggle button. I pulled the list of languages comes from [this file](https://github.com/RocketChat/Rocket.Chat/blob/0750cb6af2643fe055f31d684d13bf9b21fc799c/app/autotranslate/server/deeplTranslate.js) in the Rocket.Chat repo, but if there are more supported by Rocket.Chat, they can be added easily.
> Add code to translate toggle label

- dark-mode.css
The `::before` on blockquotes gives quotations a left margin and colored border to set them apart. In dark mode this "border" is barely visible, so I lightened it slightly.
**Edit:** I also applied this change to the "border" beside attachments, like image uploads.
Before:
After:
> Apply dark mode to block quote ::before

- dark-mode-toggle.js
- dark-mode.css
There were several goals in these changes:
1. Most importantly, switch to relying mainly on overriding Rocket.Chat CSS variables (defined [here](https://github.com/RocketChat/Rocket.Chat/blob/develop/app/theme/client/imports/general/variables.css)). Whenever overriding a variable was possible, I preferred that over writing a new CSS rule. More Rocket.Chat variables can be overridden as needed.
2. Remove redundant CSS rules (once the variables were added). This will probably be an ongoing task to make sure we're using as few rules as needed to accomplish the work.
3. Make dark mode easier for others to tweak. Rather than hunting down various rules, I wanted a few key variables to be defined which could a user could tweak to easily and consistently change the dark theme to suit their …
> Dark mode v2.0

- dark-mode-toggle.js
Previously, clicking on the dark mode toggle button would get it stuck in focus state, and the tool tip would never go away: 
This change forces the tooltip to hide after being clicked, although the hover rule still applies, so it gracefully disappears like other tooltips:
> Hide tooltip on click

- dark-mode.css
Realized I couldn't see the scrollbars in the desktop client. Figured it had to do something with WebKit specific styling in the default theme since they were fine in Firefox.
These changes are untested, as I don't have admin access to a Rocket.Chat installation. I only tried applying this CSS in Chrome's console.
> change webkit scrollbar colors to make scrollbars visible again

- dark-mode.css
Adding a small rule for the elevation tiles.
To test it, search for a channel name that has no results.
The text "No data found" was on white background initially.
> add dark background for elevation tiles

- dark-mode.css
closes #37 
I tried in https://github.com/pbaity/rocketchat-dark-mode/pull/36 to remove styles for the login page, but it looks like there have to be rules in order to keep the login page clean.
Without dark mode:
With dark mode:
> Clean up login page

- dark-mode.css
closes #41 
I was torn whether to use `--color-dark-medium` or `--color-dark`. The former is what @VVvKamper suggested in the issue above, but almost seemed too light. The latter is darker but also matches the sidebar color, which looks a little odd. I'll set it to `--color-dark-medium` since the suggestion in the issue was well-received, and if enough people complain we can change it 🙂
> Fix hover color

- dark-mode.css
In 3.4.2, the room header is styled with a bottom border rather than with box-shadow as in previous versions, resulting in this:
Applying dark mode by overwriting the `border-bottom` rule:
The color (`--color-dark-medium`) is the same as was used previously.
> Apply dark mode to header's bottom border

- dark-mode.css
fixes #52 
The new color variable `--color-darker` is the calculated middle point between the colors `--color-dark` and `--color-darkest` and helps message hover not be so bright. I think this complements the look of the message actions well too:
And it forms a nice inverse of what it looks like without dark mode:
> Update hover color; fix message actions

- dark-mode.css
The new User Profile modal has a transparent backdrop.
Before `v3.5.1`, this configuration was needed:
The new default seems to open the User Profile modal anyway.
> Settings > Layout > User Interface
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> Fix modal backdrop transparency

- dark-mode.css
fixes #49 
These rules apply to the Terms of Service, Privacy Policy, and Legal Notice pages on the login screen. Now they look like this:
> Update terms of service page colors

- dark-mode.css
This PR adds contrast to `.rc-old code.inline` nodes.
Where to find them:
`Administration > Integrations > "Click any integration"`
I added the `.rc-old` class to narrow the scope, `code.inline` seemed too broad.
Suggestions are welcome!
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> Add rc-old code inline dark mode

- dark-mode.css
This PR fixes contrast in `animation: highlight`.
To reproduce, click on a message sent in a thread (See recordings for more details).
:art: Color suggestions are welcome!
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> Fix message highlight animation

- dark-mode.css
Make it use the header-background-color variable which is also used for the entire chat window.
Before, after.
> Fix background color of the "Unread Messages" label

- dark-mode.css
Closes #69
I think, that issue was in
```
body.dark-mode .rcx-box {
background-color: var(--color-dark) !important;
}
```
In !important; line
Did try to delete !Important in that line https://github.com/pbaity/rocketchat-dark-mode/blob/master/dark-mode.css#L574 and it's work too, but I don't know what else could be affected.
So I added problem element with !Important
Now unread indicator is visible in dark mode
> Unread message indicator of Threads is invisible

- dark-mode.css
Remove the aria-label rule which does the same thing because it only works when Rocket.Chat is set to English. The new rule targets the unread icon via it's sibling element, the "following" icon/button that has the unique class `.rcx-contextual-message__follow`.
closes #69
> Add rule to target unread message indicator in threads panel

- dark-mode.css
closes #77 
Makes tables look like this:
> Add rules to style markdown tables

- CONTRIBUTING.md
3.8.0 is becoming the master branch since the most recent version of Rocket.Chat, 3.8.x, introduces breaking changes to the UI. A [3.7.2](https://github.com/pbaity/rocketchat-dark-mode/tree/3.7.2) branch has been created for anyone still using older versions of Rocket.Chat.
> Merge 3.8.0 into master

- dark-mode.css
I had to do this to make scroll bars blend in nicely with the rest of Rocket.Chat on Firefox 83 (Linux).
> Style scroll bars to avoid visual clash (especially on Firefox)

- dark-mode.css
closes #89
The text of group and me mentions was blue because of the rule styling all links in the main chat. Adding these two rules (keeping them separate so they can use their own color variables) overrides the link rule and the text appears white again.
Before:
After:
> Fix blue mention link text

- dark-mode.css
Highlight substrings with a visible color. Normally they're highlighted with the same color as `.hljs-selector-tag`, so I just added them to the rule for that class. 
Before:
After:
If anyone feels strongly that this is a terrible color choice, just let me know. I'll let this hang out for a day or two to give the community a chance to veto.
> Highlight substrings in code

- dark-mode-toggle.js
Minor modifications that could help avoiding errors, by defining and using variables instead of strings everywhere in the script
- Everywhere we want to reference the Dark Mode **global CSS class**, we use `DARK_MODE_CSS` (`"dark-mode"`)
- Everywhere we want to reference the Dark Mode **key for LocalStorage**, we use `DARK_MODE_STORAGE ` (`"dark-mode"`)
- Everywhere we want to reference the Dark Mode **icon CSS id**, we use `DARK_MODE_ICON` (`"icon-darkmode"`)
- Everywhere we want to reference the Dark Mode **button CSS id**, we use `DARK_MODE_BUTTON` (`"dark-mode-button"`)
I didn't changed them to avoid breaking people's code that could use them, but to be consistent, in my opinion `DARK_MODE_ICON` should have the value `icon-dark-mode` and `DARK_MODE_BUTTON` the value …
> Define and use variables for Dark Mode CSS selectors and LocalStorage key

- dark-mode.css
A lot of modifications, especially on breaking changes, or some forgotten parts (also, some rules were too extensive) : 
- Dark Theme for all modals
- Dark Theme for dropdowns (select, options)
- Modifications on sidebars, buttons, icons, etc. to get the same behaviour as we have in normal/light theme
I tried to separate each modification in a commit, so it can be easily reverted/reviewed if needed.
Feel free to add improvements or remarks 😉
> Dark Theme improvement & fixes for RocketChat 3.11.0

- dark-mode.css
As said in the title, I highly improved Admin/Account panels look in Dark Theme (sidebars, backgrounds, etc), and did some other minor modifications, especially on tables.
Enjoy ;)
> 3.11.x improvements : Admin/Account panels, tables and minor fixes

- dark-mode.css
I noticed no broken generated classes for the 3.13.x release.
> 3.13.x - Breadscrumbs, code in attachements, poll.bot

- dark-mode.css
fixes #131 
fixes #128 
Fixes some of the brilliant white lines that appear in dark mode in borders and buttons.
Threads menu (applies to other side menus too) before and after:
The bottom border of the channel header before and after:
Hover on top right menu buttons before and after:
Anyone and everyone is welcome to critique the colors; @fdellwing will probably be changing them soon anyway.
> Fix lines and other items that are not styled dark

- dark-mode.css
Fixes #155 
The new CSS variables are not named `typing` anymore, but are now called `activity`.
> Fixed the typing indicator for Rocket.Chat 4.x.y

- dark-mode.css
Some CSS modifications to fix things that have been broken by RC 4.3.0 😉 
Thanks to @ae5960e8-a6fc-491f-b252-898ecf59af95 for pointing some of them in #161
- Left sidebar menus (Account, Display) colors (background, text, hover)
- Message option menu (three dots) colors (hover)
- Modals
- Close button (cross icon on top right) color (hover)
- Cancel button (when `.rcx-button--ghost` class is missing) color (text) (-> #144 )
- 2FA codes display box in Account menu (background)
- ...
Don't hesitate to tell me if you find something wrong or not working as expected !
> Modifications for 4.3.0

- dark-mode-toggle.js
This PR fixes #94  and #158 :
- Selected theme (dark, light, auto) is now always applied in embedded mode
- [If top navbar is enabled in embedded mode](https://developer.rocket.chat/rocket.chat/embedded-layout), the dark mode toggle button will be added to this navbar
Details:
- The script will now search for a sidebar, or a top navbar if the sidebar is not found
- When the script couldn't find a sidebar/navbar, there was an infinite loop, and we would never reach the "apply theme" part of the code, so I moved it outside the function (and I also added a retry count to avoid this loop).
> Embedded mode improvement

- dark-mode.css
going from white on cream (#ffecad) to white on dark red
> making the purne messeges warning readable 4.8.1

- dark-mode.css
These changes make quotes great again.
New CSS classes from Rocket.Chat 5.2.0 are added to the existing ones from 5.1.x in order to make the CSS work with both versions.
Fixes https://github.com/pbaity/rocketchat-dark-mode/issues/195.
> Fix quotes in 5.2.0

- dark-mode.css
A suggestion to fix the apps page in 5.2.0.
In 5.2.0 several CSS classes changed their names. In the changes in this pull request, new CSS classes from Rocket.Chat 5.2.0 are added to the existing ones from 5.1.x in order to make the CSS work with both versions.
Fixes https://github.com/pbaity/rocketchat-dark-mode/issues/197.
> Fix apps page in 5.2.0

- dark-mode.css
Most adaptions for Rocket.Chat 5.3.0 are covered by adding CSS variables for color definitions, as described in https://github.com/pbaity/rocketchat-dark-mode/issues/204#issuecomment-1299314335.
Some additional minor tweaks were necessary (e.g. regarding messages including quotes or the "Apps" page in the backend).
Fixes #204.
> make dark mode work properly with Rocket.Chat 5.3.0
